export default {
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  htmlWhitespaceSensitivity: 'ignore',
  insertPragma: false,
  jsxSingleQuote: false,
  printWidth: 120,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  trailingComma: 'none',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  singleAttributePerLine: true,
  useTabs: false,
  vueIndentScriptAndStyle: true,
}
